package com.bdx.rainbow.gds.entity;

import java.sql.Timestamp;

public class KeywordGds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword_gds.keyword
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword_gds.total
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private Long total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword_gds.success
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private Long success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword_gds.complete
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String complete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword_gds.start_time
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private Timestamp startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword_gds.end_time
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private Timestamp endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword_gds.keyword
     *
     * @return the value of keyword_gds.keyword
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword_gds.keyword
     *
     * @param keyword the value for keyword_gds.keyword
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword_gds.total
     *
     * @return the value of keyword_gds.total
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword_gds.total
     *
     * @param total the value for keyword_gds.total
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword_gds.success
     *
     * @return the value of keyword_gds.success
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Long getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword_gds.success
     *
     * @param success the value for keyword_gds.success
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setSuccess(Long success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword_gds.complete
     *
     * @return the value of keyword_gds.complete
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword_gds.complete
     *
     * @param complete the value for keyword_gds.complete
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setComplete(String complete) {
        this.complete = complete == null ? null : complete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword_gds.start_time
     *
     * @return the value of keyword_gds.start_time
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Timestamp getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword_gds.start_time
     *
     * @param startTime the value for keyword_gds.start_time
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword_gds.end_time
     *
     * @return the value of keyword_gds.end_time
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Timestamp getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword_gds.end_time
     *
     * @param endTime the value for keyword_gds.end_time
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }
}