package com.bdx.rainbow.gds.entity;

import java.sql.Timestamp;

public class Pgds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.BARCODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.NAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.ENAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.UNSPSC
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String unspsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.BRAND
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.SPEC
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.CODE_TYPE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.WIDTH
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.HEIGT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String heigt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.DEEP
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String deep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.ORGI_COUNTRY
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String orgiCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.PRODUCT_AREA
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String productArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.PACK_MAT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String packMat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.P_TYPE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String pType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.QS_TYPE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String qsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.PRODUCTOR
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String productor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.COMPOSITION
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String composition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.PRO_STANDARD
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String proStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.VALID_DATE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String validDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.PRODUCT_PERMIT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String productPermit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.HEALTH_PERMIT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String healthPermit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.GREENFOOD_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String greenfoodCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.HEALTHFOOD_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String healthfoodCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.PRODUCT_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.UPDATE_URL
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String updateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.CREATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.UPDATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_gds.IMG
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.BARCODE
     *
     * @return the value of p_gds.BARCODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.BARCODE
     *
     * @param barcode the value for p_gds.BARCODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.NAME
     *
     * @return the value of p_gds.NAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.NAME
     *
     * @param name the value for p_gds.NAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.ENAME
     *
     * @return the value of p_gds.ENAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.ENAME
     *
     * @param ename the value for p_gds.ENAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.UNSPSC
     *
     * @return the value of p_gds.UNSPSC
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getUnspsc() {
        return unspsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.UNSPSC
     *
     * @param unspsc the value for p_gds.UNSPSC
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setUnspsc(String unspsc) {
        this.unspsc = unspsc == null ? null : unspsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.BRAND
     *
     * @return the value of p_gds.BRAND
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.BRAND
     *
     * @param brand the value for p_gds.BRAND
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.SPEC
     *
     * @return the value of p_gds.SPEC
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.SPEC
     *
     * @param spec the value for p_gds.SPEC
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.CODE_TYPE
     *
     * @return the value of p_gds.CODE_TYPE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.CODE_TYPE
     *
     * @param codeType the value for p_gds.CODE_TYPE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.WIDTH
     *
     * @return the value of p_gds.WIDTH
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.WIDTH
     *
     * @param width the value for p_gds.WIDTH
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setWidth(String width) {
        this.width = width == null ? null : width.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.HEIGT
     *
     * @return the value of p_gds.HEIGT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getHeigt() {
        return heigt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.HEIGT
     *
     * @param heigt the value for p_gds.HEIGT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setHeigt(String heigt) {
        this.heigt = heigt == null ? null : heigt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.DEEP
     *
     * @return the value of p_gds.DEEP
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getDeep() {
        return deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.DEEP
     *
     * @param deep the value for p_gds.DEEP
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setDeep(String deep) {
        this.deep = deep == null ? null : deep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.ORGI_COUNTRY
     *
     * @return the value of p_gds.ORGI_COUNTRY
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getOrgiCountry() {
        return orgiCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.ORGI_COUNTRY
     *
     * @param orgiCountry the value for p_gds.ORGI_COUNTRY
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setOrgiCountry(String orgiCountry) {
        this.orgiCountry = orgiCountry == null ? null : orgiCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.PRODUCT_AREA
     *
     * @return the value of p_gds.PRODUCT_AREA
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getProductArea() {
        return productArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.PRODUCT_AREA
     *
     * @param productArea the value for p_gds.PRODUCT_AREA
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setProductArea(String productArea) {
        this.productArea = productArea == null ? null : productArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.PACK_MAT
     *
     * @return the value of p_gds.PACK_MAT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getPackMat() {
        return packMat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.PACK_MAT
     *
     * @param packMat the value for p_gds.PACK_MAT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setPackMat(String packMat) {
        this.packMat = packMat == null ? null : packMat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.P_TYPE
     *
     * @return the value of p_gds.P_TYPE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getpType() {
        return pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.P_TYPE
     *
     * @param pType the value for p_gds.P_TYPE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setpType(String pType) {
        this.pType = pType == null ? null : pType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.QS_TYPE
     *
     * @return the value of p_gds.QS_TYPE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getQsType() {
        return qsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.QS_TYPE
     *
     * @param qsType the value for p_gds.QS_TYPE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setQsType(String qsType) {
        this.qsType = qsType == null ? null : qsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.PRODUCTOR
     *
     * @return the value of p_gds.PRODUCTOR
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getProductor() {
        return productor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.PRODUCTOR
     *
     * @param productor the value for p_gds.PRODUCTOR
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setProductor(String productor) {
        this.productor = productor == null ? null : productor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.COMPOSITION
     *
     * @return the value of p_gds.COMPOSITION
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getComposition() {
        return composition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.COMPOSITION
     *
     * @param composition the value for p_gds.COMPOSITION
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setComposition(String composition) {
        this.composition = composition == null ? null : composition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.PRO_STANDARD
     *
     * @return the value of p_gds.PRO_STANDARD
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getProStandard() {
        return proStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.PRO_STANDARD
     *
     * @param proStandard the value for p_gds.PRO_STANDARD
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setProStandard(String proStandard) {
        this.proStandard = proStandard == null ? null : proStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.VALID_DATE
     *
     * @return the value of p_gds.VALID_DATE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.VALID_DATE
     *
     * @param validDate the value for p_gds.VALID_DATE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setValidDate(String validDate) {
        this.validDate = validDate == null ? null : validDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.PRODUCT_PERMIT
     *
     * @return the value of p_gds.PRODUCT_PERMIT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getProductPermit() {
        return productPermit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.PRODUCT_PERMIT
     *
     * @param productPermit the value for p_gds.PRODUCT_PERMIT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setProductPermit(String productPermit) {
        this.productPermit = productPermit == null ? null : productPermit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.HEALTH_PERMIT
     *
     * @return the value of p_gds.HEALTH_PERMIT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getHealthPermit() {
        return healthPermit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.HEALTH_PERMIT
     *
     * @param healthPermit the value for p_gds.HEALTH_PERMIT
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setHealthPermit(String healthPermit) {
        this.healthPermit = healthPermit == null ? null : healthPermit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.GREENFOOD_CODE
     *
     * @return the value of p_gds.GREENFOOD_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getGreenfoodCode() {
        return greenfoodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.GREENFOOD_CODE
     *
     * @param greenfoodCode the value for p_gds.GREENFOOD_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setGreenfoodCode(String greenfoodCode) {
        this.greenfoodCode = greenfoodCode == null ? null : greenfoodCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.HEALTHFOOD_CODE
     *
     * @return the value of p_gds.HEALTHFOOD_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getHealthfoodCode() {
        return healthfoodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.HEALTHFOOD_CODE
     *
     * @param healthfoodCode the value for p_gds.HEALTHFOOD_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setHealthfoodCode(String healthfoodCode) {
        this.healthfoodCode = healthfoodCode == null ? null : healthfoodCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.PRODUCT_CODE
     *
     * @return the value of p_gds.PRODUCT_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.PRODUCT_CODE
     *
     * @param productCode the value for p_gds.PRODUCT_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.UPDATE_URL
     *
     * @return the value of p_gds.UPDATE_URL
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getUpdateUrl() {
        return updateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.UPDATE_URL
     *
     * @param updateUrl the value for p_gds.UPDATE_URL
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setUpdateUrl(String updateUrl) {
        this.updateUrl = updateUrl == null ? null : updateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.CREATE_TIME
     *
     * @return the value of p_gds.CREATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.CREATE_TIME
     *
     * @param createTime the value for p_gds.CREATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.UPDATE_TIME
     *
     * @return the value of p_gds.UPDATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.UPDATE_TIME
     *
     * @param updateTime the value for p_gds.UPDATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_gds.IMG
     *
     * @return the value of p_gds.IMG
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_gds.IMG
     *
     * @param img the value for p_gds.IMG
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}