package com.bdx.rainbow.gds.entity;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class PgdsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    protected String suffix = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    protected int limitClauseStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    protected int limitClauseCount = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public PgdsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setLimitClauseStart(int limitClauseStart) {
        this.limitClauseStart=limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public int getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setLimitClauseCount(int limitClauseCount) {
        this.limitClauseCount=limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public int getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBarcodeIsNull() {
            addCriterion("BARCODE is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeIsNotNull() {
            addCriterion("BARCODE is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeEqualTo(String value) {
            addCriterion("BARCODE =", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotEqualTo(String value) {
            addCriterion("BARCODE <>", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeGreaterThan(String value) {
            addCriterion("BARCODE >", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeGreaterThanOrEqualTo(String value) {
            addCriterion("BARCODE >=", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLessThan(String value) {
            addCriterion("BARCODE <", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLessThanOrEqualTo(String value) {
            addCriterion("BARCODE <=", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLike(String value) {
            addCriterion("BARCODE like", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotLike(String value) {
            addCriterion("BARCODE not like", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeIn(List<String> values) {
            addCriterion("BARCODE in", values, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotIn(List<String> values) {
            addCriterion("BARCODE not in", values, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeBetween(String value1, String value2) {
            addCriterion("BARCODE between", value1, value2, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotBetween(String value1, String value2) {
            addCriterion("BARCODE not between", value1, value2, "barcode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andEnameIsNull() {
            addCriterion("ENAME is null");
            return (Criteria) this;
        }

        public Criteria andEnameIsNotNull() {
            addCriterion("ENAME is not null");
            return (Criteria) this;
        }

        public Criteria andEnameEqualTo(String value) {
            addCriterion("ENAME =", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotEqualTo(String value) {
            addCriterion("ENAME <>", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThan(String value) {
            addCriterion("ENAME >", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThanOrEqualTo(String value) {
            addCriterion("ENAME >=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThan(String value) {
            addCriterion("ENAME <", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThanOrEqualTo(String value) {
            addCriterion("ENAME <=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLike(String value) {
            addCriterion("ENAME like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotLike(String value) {
            addCriterion("ENAME not like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameIn(List<String> values) {
            addCriterion("ENAME in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotIn(List<String> values) {
            addCriterion("ENAME not in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameBetween(String value1, String value2) {
            addCriterion("ENAME between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotBetween(String value1, String value2) {
            addCriterion("ENAME not between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andUnspscIsNull() {
            addCriterion("UNSPSC is null");
            return (Criteria) this;
        }

        public Criteria andUnspscIsNotNull() {
            addCriterion("UNSPSC is not null");
            return (Criteria) this;
        }

        public Criteria andUnspscEqualTo(String value) {
            addCriterion("UNSPSC =", value, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscNotEqualTo(String value) {
            addCriterion("UNSPSC <>", value, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscGreaterThan(String value) {
            addCriterion("UNSPSC >", value, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscGreaterThanOrEqualTo(String value) {
            addCriterion("UNSPSC >=", value, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscLessThan(String value) {
            addCriterion("UNSPSC <", value, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscLessThanOrEqualTo(String value) {
            addCriterion("UNSPSC <=", value, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscLike(String value) {
            addCriterion("UNSPSC like", value, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscNotLike(String value) {
            addCriterion("UNSPSC not like", value, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscIn(List<String> values) {
            addCriterion("UNSPSC in", values, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscNotIn(List<String> values) {
            addCriterion("UNSPSC not in", values, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscBetween(String value1, String value2) {
            addCriterion("UNSPSC between", value1, value2, "unspsc");
            return (Criteria) this;
        }

        public Criteria andUnspscNotBetween(String value1, String value2) {
            addCriterion("UNSPSC not between", value1, value2, "unspsc");
            return (Criteria) this;
        }

        public Criteria andBrandIsNull() {
            addCriterion("BRAND is null");
            return (Criteria) this;
        }

        public Criteria andBrandIsNotNull() {
            addCriterion("BRAND is not null");
            return (Criteria) this;
        }

        public Criteria andBrandEqualTo(String value) {
            addCriterion("BRAND =", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotEqualTo(String value) {
            addCriterion("BRAND <>", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThan(String value) {
            addCriterion("BRAND >", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThanOrEqualTo(String value) {
            addCriterion("BRAND >=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThan(String value) {
            addCriterion("BRAND <", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThanOrEqualTo(String value) {
            addCriterion("BRAND <=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLike(String value) {
            addCriterion("BRAND like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotLike(String value) {
            addCriterion("BRAND not like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandIn(List<String> values) {
            addCriterion("BRAND in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotIn(List<String> values) {
            addCriterion("BRAND not in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandBetween(String value1, String value2) {
            addCriterion("BRAND between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotBetween(String value1, String value2) {
            addCriterion("BRAND not between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andSpecIsNull() {
            addCriterion("SPEC is null");
            return (Criteria) this;
        }

        public Criteria andSpecIsNotNull() {
            addCriterion("SPEC is not null");
            return (Criteria) this;
        }

        public Criteria andSpecEqualTo(String value) {
            addCriterion("SPEC =", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecNotEqualTo(String value) {
            addCriterion("SPEC <>", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecGreaterThan(String value) {
            addCriterion("SPEC >", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecGreaterThanOrEqualTo(String value) {
            addCriterion("SPEC >=", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecLessThan(String value) {
            addCriterion("SPEC <", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecLessThanOrEqualTo(String value) {
            addCriterion("SPEC <=", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecLike(String value) {
            addCriterion("SPEC like", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecNotLike(String value) {
            addCriterion("SPEC not like", value, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecIn(List<String> values) {
            addCriterion("SPEC in", values, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecNotIn(List<String> values) {
            addCriterion("SPEC not in", values, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecBetween(String value1, String value2) {
            addCriterion("SPEC between", value1, value2, "spec");
            return (Criteria) this;
        }

        public Criteria andSpecNotBetween(String value1, String value2) {
            addCriterion("SPEC not between", value1, value2, "spec");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIsNull() {
            addCriterion("CODE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIsNotNull() {
            addCriterion("CODE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeEqualTo(String value) {
            addCriterion("CODE_TYPE =", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotEqualTo(String value) {
            addCriterion("CODE_TYPE <>", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThan(String value) {
            addCriterion("CODE_TYPE >", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_TYPE >=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThan(String value) {
            addCriterion("CODE_TYPE <", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThanOrEqualTo(String value) {
            addCriterion("CODE_TYPE <=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLike(String value) {
            addCriterion("CODE_TYPE like", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotLike(String value) {
            addCriterion("CODE_TYPE not like", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIn(List<String> values) {
            addCriterion("CODE_TYPE in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotIn(List<String> values) {
            addCriterion("CODE_TYPE not in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeBetween(String value1, String value2) {
            addCriterion("CODE_TYPE between", value1, value2, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotBetween(String value1, String value2) {
            addCriterion("CODE_TYPE not between", value1, value2, "codeType");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("WIDTH is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("WIDTH is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(String value) {
            addCriterion("WIDTH =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(String value) {
            addCriterion("WIDTH <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(String value) {
            addCriterion("WIDTH >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(String value) {
            addCriterion("WIDTH >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(String value) {
            addCriterion("WIDTH <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(String value) {
            addCriterion("WIDTH <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLike(String value) {
            addCriterion("WIDTH like", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotLike(String value) {
            addCriterion("WIDTH not like", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<String> values) {
            addCriterion("WIDTH in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<String> values) {
            addCriterion("WIDTH not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(String value1, String value2) {
            addCriterion("WIDTH between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(String value1, String value2) {
            addCriterion("WIDTH not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andHeigtIsNull() {
            addCriterion("HEIGT is null");
            return (Criteria) this;
        }

        public Criteria andHeigtIsNotNull() {
            addCriterion("HEIGT is not null");
            return (Criteria) this;
        }

        public Criteria andHeigtEqualTo(String value) {
            addCriterion("HEIGT =", value, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtNotEqualTo(String value) {
            addCriterion("HEIGT <>", value, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtGreaterThan(String value) {
            addCriterion("HEIGT >", value, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtGreaterThanOrEqualTo(String value) {
            addCriterion("HEIGT >=", value, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtLessThan(String value) {
            addCriterion("HEIGT <", value, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtLessThanOrEqualTo(String value) {
            addCriterion("HEIGT <=", value, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtLike(String value) {
            addCriterion("HEIGT like", value, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtNotLike(String value) {
            addCriterion("HEIGT not like", value, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtIn(List<String> values) {
            addCriterion("HEIGT in", values, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtNotIn(List<String> values) {
            addCriterion("HEIGT not in", values, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtBetween(String value1, String value2) {
            addCriterion("HEIGT between", value1, value2, "heigt");
            return (Criteria) this;
        }

        public Criteria andHeigtNotBetween(String value1, String value2) {
            addCriterion("HEIGT not between", value1, value2, "heigt");
            return (Criteria) this;
        }

        public Criteria andDeepIsNull() {
            addCriterion("DEEP is null");
            return (Criteria) this;
        }

        public Criteria andDeepIsNotNull() {
            addCriterion("DEEP is not null");
            return (Criteria) this;
        }

        public Criteria andDeepEqualTo(String value) {
            addCriterion("DEEP =", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepNotEqualTo(String value) {
            addCriterion("DEEP <>", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepGreaterThan(String value) {
            addCriterion("DEEP >", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepGreaterThanOrEqualTo(String value) {
            addCriterion("DEEP >=", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepLessThan(String value) {
            addCriterion("DEEP <", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepLessThanOrEqualTo(String value) {
            addCriterion("DEEP <=", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepLike(String value) {
            addCriterion("DEEP like", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepNotLike(String value) {
            addCriterion("DEEP not like", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepIn(List<String> values) {
            addCriterion("DEEP in", values, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepNotIn(List<String> values) {
            addCriterion("DEEP not in", values, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepBetween(String value1, String value2) {
            addCriterion("DEEP between", value1, value2, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepNotBetween(String value1, String value2) {
            addCriterion("DEEP not between", value1, value2, "deep");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryIsNull() {
            addCriterion("ORGI_COUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryIsNotNull() {
            addCriterion("ORGI_COUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryEqualTo(String value) {
            addCriterion("ORGI_COUNTRY =", value, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryNotEqualTo(String value) {
            addCriterion("ORGI_COUNTRY <>", value, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryGreaterThan(String value) {
            addCriterion("ORGI_COUNTRY >", value, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryGreaterThanOrEqualTo(String value) {
            addCriterion("ORGI_COUNTRY >=", value, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryLessThan(String value) {
            addCriterion("ORGI_COUNTRY <", value, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryLessThanOrEqualTo(String value) {
            addCriterion("ORGI_COUNTRY <=", value, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryLike(String value) {
            addCriterion("ORGI_COUNTRY like", value, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryNotLike(String value) {
            addCriterion("ORGI_COUNTRY not like", value, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryIn(List<String> values) {
            addCriterion("ORGI_COUNTRY in", values, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryNotIn(List<String> values) {
            addCriterion("ORGI_COUNTRY not in", values, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryBetween(String value1, String value2) {
            addCriterion("ORGI_COUNTRY between", value1, value2, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andOrgiCountryNotBetween(String value1, String value2) {
            addCriterion("ORGI_COUNTRY not between", value1, value2, "orgiCountry");
            return (Criteria) this;
        }

        public Criteria andProductAreaIsNull() {
            addCriterion("PRODUCT_AREA is null");
            return (Criteria) this;
        }

        public Criteria andProductAreaIsNotNull() {
            addCriterion("PRODUCT_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andProductAreaEqualTo(String value) {
            addCriterion("PRODUCT_AREA =", value, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaNotEqualTo(String value) {
            addCriterion("PRODUCT_AREA <>", value, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaGreaterThan(String value) {
            addCriterion("PRODUCT_AREA >", value, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_AREA >=", value, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaLessThan(String value) {
            addCriterion("PRODUCT_AREA <", value, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_AREA <=", value, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaLike(String value) {
            addCriterion("PRODUCT_AREA like", value, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaNotLike(String value) {
            addCriterion("PRODUCT_AREA not like", value, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaIn(List<String> values) {
            addCriterion("PRODUCT_AREA in", values, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaNotIn(List<String> values) {
            addCriterion("PRODUCT_AREA not in", values, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaBetween(String value1, String value2) {
            addCriterion("PRODUCT_AREA between", value1, value2, "productArea");
            return (Criteria) this;
        }

        public Criteria andProductAreaNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_AREA not between", value1, value2, "productArea");
            return (Criteria) this;
        }

        public Criteria andPackMatIsNull() {
            addCriterion("PACK_MAT is null");
            return (Criteria) this;
        }

        public Criteria andPackMatIsNotNull() {
            addCriterion("PACK_MAT is not null");
            return (Criteria) this;
        }

        public Criteria andPackMatEqualTo(String value) {
            addCriterion("PACK_MAT =", value, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatNotEqualTo(String value) {
            addCriterion("PACK_MAT <>", value, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatGreaterThan(String value) {
            addCriterion("PACK_MAT >", value, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatGreaterThanOrEqualTo(String value) {
            addCriterion("PACK_MAT >=", value, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatLessThan(String value) {
            addCriterion("PACK_MAT <", value, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatLessThanOrEqualTo(String value) {
            addCriterion("PACK_MAT <=", value, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatLike(String value) {
            addCriterion("PACK_MAT like", value, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatNotLike(String value) {
            addCriterion("PACK_MAT not like", value, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatIn(List<String> values) {
            addCriterion("PACK_MAT in", values, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatNotIn(List<String> values) {
            addCriterion("PACK_MAT not in", values, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatBetween(String value1, String value2) {
            addCriterion("PACK_MAT between", value1, value2, "packMat");
            return (Criteria) this;
        }

        public Criteria andPackMatNotBetween(String value1, String value2) {
            addCriterion("PACK_MAT not between", value1, value2, "packMat");
            return (Criteria) this;
        }

        public Criteria andPTypeIsNull() {
            addCriterion("P_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPTypeIsNotNull() {
            addCriterion("P_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPTypeEqualTo(String value) {
            addCriterion("P_TYPE =", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotEqualTo(String value) {
            addCriterion("P_TYPE <>", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeGreaterThan(String value) {
            addCriterion("P_TYPE >", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeGreaterThanOrEqualTo(String value) {
            addCriterion("P_TYPE >=", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLessThan(String value) {
            addCriterion("P_TYPE <", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLessThanOrEqualTo(String value) {
            addCriterion("P_TYPE <=", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLike(String value) {
            addCriterion("P_TYPE like", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotLike(String value) {
            addCriterion("P_TYPE not like", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeIn(List<String> values) {
            addCriterion("P_TYPE in", values, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotIn(List<String> values) {
            addCriterion("P_TYPE not in", values, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeBetween(String value1, String value2) {
            addCriterion("P_TYPE between", value1, value2, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotBetween(String value1, String value2) {
            addCriterion("P_TYPE not between", value1, value2, "pType");
            return (Criteria) this;
        }

        public Criteria andQsTypeIsNull() {
            addCriterion("QS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andQsTypeIsNotNull() {
            addCriterion("QS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andQsTypeEqualTo(String value) {
            addCriterion("QS_TYPE =", value, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeNotEqualTo(String value) {
            addCriterion("QS_TYPE <>", value, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeGreaterThan(String value) {
            addCriterion("QS_TYPE >", value, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("QS_TYPE >=", value, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeLessThan(String value) {
            addCriterion("QS_TYPE <", value, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeLessThanOrEqualTo(String value) {
            addCriterion("QS_TYPE <=", value, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeLike(String value) {
            addCriterion("QS_TYPE like", value, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeNotLike(String value) {
            addCriterion("QS_TYPE not like", value, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeIn(List<String> values) {
            addCriterion("QS_TYPE in", values, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeNotIn(List<String> values) {
            addCriterion("QS_TYPE not in", values, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeBetween(String value1, String value2) {
            addCriterion("QS_TYPE between", value1, value2, "qsType");
            return (Criteria) this;
        }

        public Criteria andQsTypeNotBetween(String value1, String value2) {
            addCriterion("QS_TYPE not between", value1, value2, "qsType");
            return (Criteria) this;
        }

        public Criteria andProductorIsNull() {
            addCriterion("PRODUCTOR is null");
            return (Criteria) this;
        }

        public Criteria andProductorIsNotNull() {
            addCriterion("PRODUCTOR is not null");
            return (Criteria) this;
        }

        public Criteria andProductorEqualTo(String value) {
            addCriterion("PRODUCTOR =", value, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorNotEqualTo(String value) {
            addCriterion("PRODUCTOR <>", value, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorGreaterThan(String value) {
            addCriterion("PRODUCTOR >", value, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCTOR >=", value, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorLessThan(String value) {
            addCriterion("PRODUCTOR <", value, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorLessThanOrEqualTo(String value) {
            addCriterion("PRODUCTOR <=", value, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorLike(String value) {
            addCriterion("PRODUCTOR like", value, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorNotLike(String value) {
            addCriterion("PRODUCTOR not like", value, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorIn(List<String> values) {
            addCriterion("PRODUCTOR in", values, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorNotIn(List<String> values) {
            addCriterion("PRODUCTOR not in", values, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorBetween(String value1, String value2) {
            addCriterion("PRODUCTOR between", value1, value2, "productor");
            return (Criteria) this;
        }

        public Criteria andProductorNotBetween(String value1, String value2) {
            addCriterion("PRODUCTOR not between", value1, value2, "productor");
            return (Criteria) this;
        }

        public Criteria andCompositionIsNull() {
            addCriterion("COMPOSITION is null");
            return (Criteria) this;
        }

        public Criteria andCompositionIsNotNull() {
            addCriterion("COMPOSITION is not null");
            return (Criteria) this;
        }

        public Criteria andCompositionEqualTo(String value) {
            addCriterion("COMPOSITION =", value, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionNotEqualTo(String value) {
            addCriterion("COMPOSITION <>", value, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionGreaterThan(String value) {
            addCriterion("COMPOSITION >", value, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionGreaterThanOrEqualTo(String value) {
            addCriterion("COMPOSITION >=", value, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionLessThan(String value) {
            addCriterion("COMPOSITION <", value, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionLessThanOrEqualTo(String value) {
            addCriterion("COMPOSITION <=", value, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionLike(String value) {
            addCriterion("COMPOSITION like", value, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionNotLike(String value) {
            addCriterion("COMPOSITION not like", value, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionIn(List<String> values) {
            addCriterion("COMPOSITION in", values, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionNotIn(List<String> values) {
            addCriterion("COMPOSITION not in", values, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionBetween(String value1, String value2) {
            addCriterion("COMPOSITION between", value1, value2, "composition");
            return (Criteria) this;
        }

        public Criteria andCompositionNotBetween(String value1, String value2) {
            addCriterion("COMPOSITION not between", value1, value2, "composition");
            return (Criteria) this;
        }

        public Criteria andProStandardIsNull() {
            addCriterion("PRO_STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andProStandardIsNotNull() {
            addCriterion("PRO_STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andProStandardEqualTo(String value) {
            addCriterion("PRO_STANDARD =", value, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardNotEqualTo(String value) {
            addCriterion("PRO_STANDARD <>", value, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardGreaterThan(String value) {
            addCriterion("PRO_STANDARD >", value, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardGreaterThanOrEqualTo(String value) {
            addCriterion("PRO_STANDARD >=", value, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardLessThan(String value) {
            addCriterion("PRO_STANDARD <", value, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardLessThanOrEqualTo(String value) {
            addCriterion("PRO_STANDARD <=", value, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardLike(String value) {
            addCriterion("PRO_STANDARD like", value, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardNotLike(String value) {
            addCriterion("PRO_STANDARD not like", value, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardIn(List<String> values) {
            addCriterion("PRO_STANDARD in", values, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardNotIn(List<String> values) {
            addCriterion("PRO_STANDARD not in", values, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardBetween(String value1, String value2) {
            addCriterion("PRO_STANDARD between", value1, value2, "proStandard");
            return (Criteria) this;
        }

        public Criteria andProStandardNotBetween(String value1, String value2) {
            addCriterion("PRO_STANDARD not between", value1, value2, "proStandard");
            return (Criteria) this;
        }

        public Criteria andValidDateIsNull() {
            addCriterion("VALID_DATE is null");
            return (Criteria) this;
        }

        public Criteria andValidDateIsNotNull() {
            addCriterion("VALID_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andValidDateEqualTo(String value) {
            addCriterion("VALID_DATE =", value, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateNotEqualTo(String value) {
            addCriterion("VALID_DATE <>", value, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateGreaterThan(String value) {
            addCriterion("VALID_DATE >", value, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateGreaterThanOrEqualTo(String value) {
            addCriterion("VALID_DATE >=", value, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateLessThan(String value) {
            addCriterion("VALID_DATE <", value, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateLessThanOrEqualTo(String value) {
            addCriterion("VALID_DATE <=", value, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateLike(String value) {
            addCriterion("VALID_DATE like", value, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateNotLike(String value) {
            addCriterion("VALID_DATE not like", value, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateIn(List<String> values) {
            addCriterion("VALID_DATE in", values, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateNotIn(List<String> values) {
            addCriterion("VALID_DATE not in", values, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateBetween(String value1, String value2) {
            addCriterion("VALID_DATE between", value1, value2, "validDate");
            return (Criteria) this;
        }

        public Criteria andValidDateNotBetween(String value1, String value2) {
            addCriterion("VALID_DATE not between", value1, value2, "validDate");
            return (Criteria) this;
        }

        public Criteria andProductPermitIsNull() {
            addCriterion("PRODUCT_PERMIT is null");
            return (Criteria) this;
        }

        public Criteria andProductPermitIsNotNull() {
            addCriterion("PRODUCT_PERMIT is not null");
            return (Criteria) this;
        }

        public Criteria andProductPermitEqualTo(String value) {
            addCriterion("PRODUCT_PERMIT =", value, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitNotEqualTo(String value) {
            addCriterion("PRODUCT_PERMIT <>", value, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitGreaterThan(String value) {
            addCriterion("PRODUCT_PERMIT >", value, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_PERMIT >=", value, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitLessThan(String value) {
            addCriterion("PRODUCT_PERMIT <", value, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_PERMIT <=", value, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitLike(String value) {
            addCriterion("PRODUCT_PERMIT like", value, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitNotLike(String value) {
            addCriterion("PRODUCT_PERMIT not like", value, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitIn(List<String> values) {
            addCriterion("PRODUCT_PERMIT in", values, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitNotIn(List<String> values) {
            addCriterion("PRODUCT_PERMIT not in", values, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitBetween(String value1, String value2) {
            addCriterion("PRODUCT_PERMIT between", value1, value2, "productPermit");
            return (Criteria) this;
        }

        public Criteria andProductPermitNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_PERMIT not between", value1, value2, "productPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitIsNull() {
            addCriterion("HEALTH_PERMIT is null");
            return (Criteria) this;
        }

        public Criteria andHealthPermitIsNotNull() {
            addCriterion("HEALTH_PERMIT is not null");
            return (Criteria) this;
        }

        public Criteria andHealthPermitEqualTo(String value) {
            addCriterion("HEALTH_PERMIT =", value, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitNotEqualTo(String value) {
            addCriterion("HEALTH_PERMIT <>", value, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitGreaterThan(String value) {
            addCriterion("HEALTH_PERMIT >", value, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitGreaterThanOrEqualTo(String value) {
            addCriterion("HEALTH_PERMIT >=", value, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitLessThan(String value) {
            addCriterion("HEALTH_PERMIT <", value, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitLessThanOrEqualTo(String value) {
            addCriterion("HEALTH_PERMIT <=", value, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitLike(String value) {
            addCriterion("HEALTH_PERMIT like", value, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitNotLike(String value) {
            addCriterion("HEALTH_PERMIT not like", value, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitIn(List<String> values) {
            addCriterion("HEALTH_PERMIT in", values, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitNotIn(List<String> values) {
            addCriterion("HEALTH_PERMIT not in", values, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitBetween(String value1, String value2) {
            addCriterion("HEALTH_PERMIT between", value1, value2, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andHealthPermitNotBetween(String value1, String value2) {
            addCriterion("HEALTH_PERMIT not between", value1, value2, "healthPermit");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeIsNull() {
            addCriterion("GREENFOOD_CODE is null");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeIsNotNull() {
            addCriterion("GREENFOOD_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeEqualTo(String value) {
            addCriterion("GREENFOOD_CODE =", value, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeNotEqualTo(String value) {
            addCriterion("GREENFOOD_CODE <>", value, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeGreaterThan(String value) {
            addCriterion("GREENFOOD_CODE >", value, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeGreaterThanOrEqualTo(String value) {
            addCriterion("GREENFOOD_CODE >=", value, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeLessThan(String value) {
            addCriterion("GREENFOOD_CODE <", value, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeLessThanOrEqualTo(String value) {
            addCriterion("GREENFOOD_CODE <=", value, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeLike(String value) {
            addCriterion("GREENFOOD_CODE like", value, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeNotLike(String value) {
            addCriterion("GREENFOOD_CODE not like", value, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeIn(List<String> values) {
            addCriterion("GREENFOOD_CODE in", values, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeNotIn(List<String> values) {
            addCriterion("GREENFOOD_CODE not in", values, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeBetween(String value1, String value2) {
            addCriterion("GREENFOOD_CODE between", value1, value2, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andGreenfoodCodeNotBetween(String value1, String value2) {
            addCriterion("GREENFOOD_CODE not between", value1, value2, "greenfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeIsNull() {
            addCriterion("HEALTHFOOD_CODE is null");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeIsNotNull() {
            addCriterion("HEALTHFOOD_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeEqualTo(String value) {
            addCriterion("HEALTHFOOD_CODE =", value, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeNotEqualTo(String value) {
            addCriterion("HEALTHFOOD_CODE <>", value, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeGreaterThan(String value) {
            addCriterion("HEALTHFOOD_CODE >", value, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeGreaterThanOrEqualTo(String value) {
            addCriterion("HEALTHFOOD_CODE >=", value, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeLessThan(String value) {
            addCriterion("HEALTHFOOD_CODE <", value, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeLessThanOrEqualTo(String value) {
            addCriterion("HEALTHFOOD_CODE <=", value, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeLike(String value) {
            addCriterion("HEALTHFOOD_CODE like", value, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeNotLike(String value) {
            addCriterion("HEALTHFOOD_CODE not like", value, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeIn(List<String> values) {
            addCriterion("HEALTHFOOD_CODE in", values, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeNotIn(List<String> values) {
            addCriterion("HEALTHFOOD_CODE not in", values, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeBetween(String value1, String value2) {
            addCriterion("HEALTHFOOD_CODE between", value1, value2, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andHealthfoodCodeNotBetween(String value1, String value2) {
            addCriterion("HEALTHFOOD_CODE not between", value1, value2, "healthfoodCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("PRODUCT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("PRODUCT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("PRODUCT_CODE =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("PRODUCT_CODE <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("PRODUCT_CODE >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_CODE >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("PRODUCT_CODE <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_CODE <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("PRODUCT_CODE like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("PRODUCT_CODE not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("PRODUCT_CODE in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("PRODUCT_CODE not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("PRODUCT_CODE between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_CODE not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlIsNull() {
            addCriterion("UPDATE_URL is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlIsNotNull() {
            addCriterion("UPDATE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlEqualTo(String value) {
            addCriterion("UPDATE_URL =", value, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlNotEqualTo(String value) {
            addCriterion("UPDATE_URL <>", value, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlGreaterThan(String value) {
            addCriterion("UPDATE_URL >", value, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_URL >=", value, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlLessThan(String value) {
            addCriterion("UPDATE_URL <", value, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_URL <=", value, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlLike(String value) {
            addCriterion("UPDATE_URL like", value, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlNotLike(String value) {
            addCriterion("UPDATE_URL not like", value, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlIn(List<String> values) {
            addCriterion("UPDATE_URL in", values, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlNotIn(List<String> values) {
            addCriterion("UPDATE_URL not in", values, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlBetween(String value1, String value2) {
            addCriterion("UPDATE_URL between", value1, value2, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andUpdateUrlNotBetween(String value1, String value2) {
            addCriterion("UPDATE_URL not between", value1, value2, "updateUrl");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Timestamp value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Timestamp value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Timestamp> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Timestamp> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("IMG is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("IMG is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("IMG =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("IMG <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("IMG >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("IMG >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("IMG <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("IMG <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("IMG like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("IMG not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("IMG in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("IMG not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("IMG between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("IMG not between", value1, value2, "img");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table p_gds
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 16 12:10:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table p_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}