package com.bdx.rainbow.gds.entity;

import java.sql.Timestamp;

public class ProductorGds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productor_gds.P_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productor_gds.NAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productor_gds.ENAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productor_gds.ADDRESS
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productor_gds.EADDRESS
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String eaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productor_gds.POSTCODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productor_gds.UPDATE_URL
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private String updateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productor_gds.CREATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productor_gds.UPDATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productor_gds.P_CODE
     *
     * @return the value of productor_gds.P_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productor_gds.P_CODE
     *
     * @param pCode the value for productor_gds.P_CODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productor_gds.NAME
     *
     * @return the value of productor_gds.NAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productor_gds.NAME
     *
     * @param name the value for productor_gds.NAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productor_gds.ENAME
     *
     * @return the value of productor_gds.ENAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productor_gds.ENAME
     *
     * @param ename the value for productor_gds.ENAME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productor_gds.ADDRESS
     *
     * @return the value of productor_gds.ADDRESS
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productor_gds.ADDRESS
     *
     * @param address the value for productor_gds.ADDRESS
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productor_gds.EADDRESS
     *
     * @return the value of productor_gds.EADDRESS
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getEaddress() {
        return eaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productor_gds.EADDRESS
     *
     * @param eaddress the value for productor_gds.EADDRESS
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setEaddress(String eaddress) {
        this.eaddress = eaddress == null ? null : eaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productor_gds.POSTCODE
     *
     * @return the value of productor_gds.POSTCODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productor_gds.POSTCODE
     *
     * @param postcode the value for productor_gds.POSTCODE
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productor_gds.UPDATE_URL
     *
     * @return the value of productor_gds.UPDATE_URL
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public String getUpdateUrl() {
        return updateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productor_gds.UPDATE_URL
     *
     * @param updateUrl the value for productor_gds.UPDATE_URL
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setUpdateUrl(String updateUrl) {
        this.updateUrl = updateUrl == null ? null : updateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productor_gds.CREATE_TIME
     *
     * @return the value of productor_gds.CREATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productor_gds.CREATE_TIME
     *
     * @param createTime the value for productor_gds.CREATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productor_gds.UPDATE_TIME
     *
     * @return the value of productor_gds.UPDATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productor_gds.UPDATE_TIME
     *
     * @param updateTime the value for productor_gds.UPDATE_TIME
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}