package com.bdx.rainbow.gds.mapper;

import com.bdx.rainbow.gds.entity.KeywordGds;
import com.bdx.rainbow.gds.entity.KeywordGdsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KeywordGdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int countByExample(KeywordGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int deleteByExample(KeywordGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int deleteByPrimaryKey(String keyword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int insert(KeywordGds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int insertSelective(KeywordGds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    List<KeywordGds> selectByExample(KeywordGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    KeywordGds selectByPrimaryKey(String keyword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") KeywordGds record, @Param("example") KeywordGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int updateByExample(@Param("record") KeywordGds record, @Param("example") KeywordGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int updateByPrimaryKeySelective(KeywordGds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int updateByPrimaryKey(KeywordGds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    void insertBatch(List<KeywordGds> recordLst);
}