package com.bdx.rainbow.gds.mapper;

import com.bdx.rainbow.gds.entity.ProductorGds;
import com.bdx.rainbow.gds.entity.ProductorGdsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductorGdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int countByExample(ProductorGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int deleteByExample(ProductorGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int deleteByPrimaryKey(String pCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int insert(ProductorGds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int insertSelective(ProductorGds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    List<ProductorGds> selectByExample(ProductorGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    ProductorGds selectByPrimaryKey(String pCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProductorGds record, @Param("example") ProductorGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int updateByExample(@Param("record") ProductorGds record, @Param("example") ProductorGdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int updateByPrimaryKeySelective(ProductorGds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    int updateByPrimaryKey(ProductorGds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productor_gds
     *
     * @mbggenerated Sat Apr 16 12:10:59 CST 2016
     */
    void insertBatch(List<ProductorGds> recordLst);
}